packages:
  - services/*
  - packages/*
  - tools/bblimport
  - tools/tpdownload
  - tools/tpimport

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - prisma
  - puppeteer
  - unrs-resolver
