packages:
  - services/*
  - packages/*
  - tools/bblimport
  - tools/tpdownload
  - tools/tpimport

allowBuilds:
  '@nestjs/core': true
  '@prisma/client': true
  '@prisma/engines': true
  prisma: true
  puppeteer: true
  unrs-resolver: true

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - prisma
  - puppeteer
  - unrs-resolver
