packages:
  - services/*
  - packages/*
  - bblimport
  - tpdownload
  - tpimport

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - prisma
  - puppeteer
  - unrs-resolver
